version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:10.15.3

    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build
      - run: git config user.email "TakaShinoda+circleci@users.noreply.github.com"
      - run: git config user.name "TakaShinoda+circleci"
      - run:
          name: Deploy
          command: yarn deploy:local
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/